sudo: required

services: 
  - docker

before_install:
  - docker build -t cirant3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cirant3/react-test npm test -- --coverage

after_success:
  - docker build -t cirant3/multi-client ./client
  - docker build -t cirant3/multi-nginx ./nginx
  - docker build -t cirant3/multi-server ./server
  - docker build -t cirant3/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cirant3/multi-client
  - docker push cirant3/multi-nginx
  - docker push cirant3/multi-server
  - docker push cirant3/multi-worker

language: generic 