sudo: required

services: 
  - docker

before_install:
  - docker build -t cirant3/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cirant3/react-test npm test -- --coverage

after_success:
  - docker build -t cirant3/multi-client ./client
  - docker build -t cirant3/multi-nginx ./nginx
  - docker build -t cirant3/multi-server ./server
  - docker build -t cirant3/multi-worker ./worker

  # login in docker to be able to push images 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cirant3/multi-client
  - docker push cirant3/multi-nginx
  - docker push cirant3/multi-server
  - docker push cirant3/multi-worker

language: generic 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-270214867126
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    